---
- name: printing variables from var files
  hosts: local
  connection: local
  vars_files:
  - /Devops/varfiles.yaml
  tasks:
  - name: 01. print variables
    ansible.builtin.debug:
      msg: "A: {{ A }} B: {{ B }} C: {{ C }}"
