---
- name: variable
  hosts: local
  connection: local
  vars:
    A: 10
    B: 20
    C: 30
  tasks:
  - name: 01. printing variables
    ansible.builtin.debug:
      msg: " A: {{A}}, B: {{B}}, C: {{C}}"
